### ISSUE TITLE
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion

### ISSUE THREAD

**Issue by tanuki-billie** [aretegames/arete-engine#5]
When attempting to run the example rust project on macOS, I get the following errors:
```
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor: MTLResourceStorageModeMemoryless is not a supported storage mode on this device.
MTLTextureDescriptor: Depth, Stencil, DepthStencil textures cannot be allocated with MTLResourceStorageModeMemoryless on this device.
'
```

# Steps to reproduce
1. Download the macOS prerelease build
2. Run `./run-macos.sh` in either `game-rust` or `game-cpp`
3. Witness Arete crash

# System specs
MacBook Pro, 13 inch, 2020, Four Thunderbolt ports
Processor: 2 GHz Quad-Core Intel Core i5
Graphics: Intel Iris Plus Graphics 1536 MB
Memory: 16 GB 3733 MHz LPDDR4X
macOS version: 14.0 Sonoma

**Comment by jamesordner** [comment]
Ah you're using an Intel mac. We haven't tested on one of those in a while, thanks for the report! Fix is as simple as checking a property and setting a flag :)
